version: 1
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
flags:
  - -trimpath
goos: windows
goarch: arm64
ldflags:
  - "-s -w"
  - "-X main.version={{ .Env.VERSION }}"
  - "-X main.commit={{ .Env.COMMIT }}"
main: ./cmd/gitea2forgejo
binary: gitea2forgejo-windows-arm64.exe
